version: "3.6"

services:
  postgres:
    image: postgres
    container_name: cafe-shop
    environment:
      POSTGRES_DB: cafe-shop
      POSTGRES_USER: cafe-shop
      POSTGRES_PASSWORD: Summer@2024
    command: -c synchronous_commit=off --max-connections=200 --shared-buffers=4GB --work-mem=20MB
    ports:
      - 5434:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  cafe_shop_microservices:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: cafe-shop-app
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/cafe-shop
      SPRING_DATASOURCE_USERNAME: cafe-shop
      SPRING_DATASOURCE_PASSWORD: Summer@2024
    depends_on:
      - postgres

volumes:
  postgres_data: